const motivationalQuotes = [
  // Leadership & Success
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
  "Leadership is not about being the best. Leadership is about making everyone else better. - Anonymous",
  "The question isn't who's going to let me; it's who is going to stop me. - Ayn Rand",
  "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "Innovation distinguishes between a leader and a follower. - Steve Jobs",
  "The best way to predict the future is to create it. - Peter Drucker",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "A leader is one who knows the way, goes the way, and shows the way. - John C. Maxwell",

  // Perseverance & Determination
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "The harder I work, the luckier I get. - Samuel Goldwyn",
  "Perseverance is not a long race; it is many short races one after another. - Walter Elliott",
  "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
  "Fall seven times, stand up eight. - Japanese Proverb",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Tough times never last, but tough people do. - Robert H. Schuller",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "The difference between try and triumph is just a little umph! - Marvin Phillips",
  "Success seems to be connected with action. Successful people keep moving. - Conrad Hilton",

  // Personal Growth & Self-Improvement
  "Be not afraid of growing slowly; be afraid only of standing still. - Chinese Proverb",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
  "Life is 10% what happens to you and 90% how you react to it. - Charles R. Swindoll",
  "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
  "Do something today that your future self will thank you for. - Anonymous",
  "Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don't belong. - Anonymous",
  "The expert in anything was once a beginner. - Helen Hayes",
  "Your life does not get better by chance, it gets better by change. - Jim Rohn",
  "Everything you've ever wanted is on the other side of fear. - George Addair",

  // Dreams & Aspirations
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "Dream bigger. Do bigger. - Anonymous",
  "All our dreams can come true if we have the courage to pursue them. - Walt Disney",
  "If you can dream it, you can do it. - Walt Disney",
  "The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "Chase your dreams but always know the road that will lead you home again. - Anonymous",
  "Follow your dreams, they know the way. - Kobe Yamada",
  "The dream is free. The hustle is sold separately. - Anonymous",
  "Your dreams don't work unless you do. - John C. Maxwell",

  // Time & Action
  "The best way to get started is to quit talking and begin doing. - Walt Disney",
  "Don't count the days, make the days count. - Muhammad Ali",
  "Yesterday you said tomorrow. Just do it. - Nike",
  "Time is a created thing. To say 'I don't have time' is to say 'I don't want to.' - Lao Tzu",
  "The future depends on what you do today. - Mahatma Gandhi",
  "Don't wait. The time will never be just right. - Napoleon Hill",
  "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
  "Time waits for no one. - Anonymous",
  "The two most powerful warriors are patience and time. - Leo Tolstoy",
  "Lost time is never found again. - Benjamin Franklin",

  // Mindset & Attitude
  "Whether you think you can or you think you can't, you're right. - Henry Ford",
  "Change your thoughts and you change your world. - Norman Vincent Peale",
  "Your attitude determines your direction. - Anonymous",
  "A positive attitude causes a chain reaction of positive thoughts, events, and outcomes. - Wade Boggs",
  "Life is 10% what happens to us and 90% how we react to it. - Dennis P. Kimbro",
  "The mind is everything. What you think you become. - Buddha",
  "Your attitude, not your aptitude, will determine your altitude. - Zig Ziglar",
  "Positive anything is better than negative nothing. - Elbert Hubbard",
  "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
  "A bad attitude is like a flat tire. You can't go anywhere until you change it. - Anonymous",

  // Courage & Fear
  "Courage is resistance to fear, mastery of fear—not absence of fear. - Mark Twain",
  "Fear is a reaction. Courage is a decision. - Winston Churchill",
  "Don't let your fear of what could happen make nothing happen. - Anonymous",
  "Everything you want is on the other side of fear. - Jack Canfield",
  "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying 'I will try again tomorrow.' - Mary Anne Radmacher",
  "Being brave isn't the absence of fear. Being brave is having that fear but finding a way through it. - Bear Grylls",
  "Fear kills more dreams than failure ever will. - Anonymous",
  "The brave man is not he who does not feel afraid, but he who conquers that fear. - Nelson Mandela",
  "Do one thing every day that scares you. - Eleanor Roosevelt",
  "Fear is temporary. Regret is forever. - Anonymous",

  // Persistence & Never Giving Up
  "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway. - Earl Nightingale",
  "It's not about perfect. It's about effort. - Jillian Michaels",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. - Thomas A. Edison",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "Never give up on something that you can't go a day without thinking about. - Winston Churchill",
  "The difference between a successful person and others is not lack of strength not a lack of knowledge but rather a lack in will. - Vince Lombardi",
  "Success seems to be largely a matter of hanging on after others have let go. - William Feather",
  "When you feel like giving up, remember why you held on for so long in the first place. - Anonymous",

  // Growth & Challenge
  "Life begins at the end of your comfort zone. - Neale Donald Walsch",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "If it doesn't challenge you, it doesn't change you. - Fred DeVito",
  "Growth and comfort do not coexist. - Ginni Rometty",
  "Comfort zones are beautiful places but nothing grows there. - Anonymous",
  "Challenge yourself everyday to do better and be better. Remember, growth starts with a decision to move beyond your present circumstances. - Robert Tew",
  "Don't be afraid to start over. It's a chance to build something better this time. - Anonymous",
  "The greatest pleasure in life is doing what people say you cannot do. - Walter Bagehot",
  "If you're not challenging yourself, you're not changing yourself. - Anonymous",
  "Growth is the only evidence of life. - John Henry Newman",

  // Purpose & Meaning
  "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
  "Purpose is the reason you journey. Passion is the fire that lights your way. - Anonymous",
  "When you know your why, you'll find your way. - Anonymous",
  "Life is not about finding yourself. Life is about creating yourself. - George Bernard Shaw",
  "The meaning of life is to find your gift. The purpose of life is to give it away. - Pablo Picasso",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - Steve Jobs",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate. - Ralph Waldo Emerson",
  "Don't ask what the world needs. Ask what makes you come alive and go do it. - Howard Thurman",
  "The purpose of life is a life of purpose. - Robert Byrne",
  "Find something worth fighting for and live for it. - Anonymous",

  // Wisdom & Learning
  "The only true wisdom is in knowing you know nothing. - Socrates",
  "Knowledge speaks, but wisdom listens. - Jimi Hendrix",
  "Learn from yesterday, live for today, hope for tomorrow. - Albert Einstein",
  "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice. - Brian Herbert",
  "Education is not the learning of facts, but the training of the mind to think. - Albert Einstein",
  "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
  "The more that you read, the more things you will know. The more that you learn, the more places you'll go. - Dr. Seuss",
  "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young. - Henry Ford",
  "Learning is not attained by chance, it must be sought for with ardor and attended to with diligence. - Abigail Adams",
  "The beautiful thing about learning is that nobody can take it away from you. - B.B. King",

  // Change & Adaptation
  "Change is the law of life. And those who look only to the past or present are certain to miss the future. - John F. Kennedy",
  "The only way to make sense out of change is to plunge into it, move with it, and join the dance. - Alan Watts",
  "Progress is impossible without change, and those who cannot change their minds cannot change anything. - George Bernard Shaw",
  "Change before you have to. - Jack Welch",
  "The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking. - Albert Einstein",
  "If you don't like something, change it. If you can't change it, change your attitude. - Maya Angelou",
  "Those who cannot change their minds cannot change anything. - George Bernard Shaw",
  "Change is painful, but nothing is as painful as staying stuck somewhere you don't belong. - Mandy Hale",
  "The secret of change is to focus all of your energy not on fighting the old, but on building the new. - Socrates",
  "Life is a series of natural and spontaneous changes. Don't resist them; that only creates sorrow. - Lao Tzu",

  // Focus & Discipline
  "Discipline is the bridge between goals and accomplishment. - Jim Rohn",
  "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
  "It is not enough to be busy... The question is: what are we busy about? - Henry David Thoreau",
  "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus. - Alexander Graham Bell",
  "Focus on being productive instead of busy. - Tim Ferriss",
  "Where focus goes, energy flows. - Tony Robbins",
  "The more you sweat in practice, the less you bleed in battle. - Richard Marcinko",
  "Self-discipline is the magic power that makes you virtually unstoppable. - Dan Kennedy",
  "Success is about dedication. You may not be where you want to be or do what you want to do when you're on the journey. But you've got to be willing to have vision and foresight that leads you to an incredible end. - Usher",
  "Focus is a matter of deciding what things you're not going to do. - John Carmack",

  // Resilience & Adversity
  "The gem cannot be polished without friction, nor man perfected without trials. - Chinese Proverb",
  "Life is not about waiting for the storms to pass. It's about learning how to dance in the rain. - Vivian Greene",
  "The oak fought the wind and was broken, the willow bent when it must and survived. - Robert Jordan",
  "When we learn how to become resilient, we learn how to embrace the beautifully broad spectrum of the human experience. - Jaeda Dewalt",
  "Rock bottom became the solid foundation on which I rebuilt my life. - J.K. Rowling",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
  "In the middle of difficulty lies opportunity. - Albert Einstein",
  "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired, and success achieved. - Helen Keller",
  "Life doesn't get easier or more forgiving; we get stronger and more resilient. - Steve Maraboli",

  // Vision & Goals
  "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
  "A goal is not always meant to be reached; it often serves simply as something to aim at. - Bruce Lee",
  "The greater danger for most of us lies not in setting our aim too high and falling short, but in setting our aim too low, and achieving our mark. - Michelangelo",
  "Vision without action is merely a dream. Action without vision just passes the time. Vision with action can change the world. - Joel A. Barker",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "Don't lower your expectations to meet your performance. Raise your level of performance to meet your expectations. - Ralph Marston",
  "Goals are dreams with deadlines. - Diana Scharf",
  "Your goals are the road maps that guide you and show you what is possible for your life. - Les Brown",
  "If you aim at nothing, you will hit it every time. - Zig Ziglar",
  "The trouble with not having a goal is that you can spend your life running up and down the field and never score. - Bill Copeland",

  // Innovation & Creativity
  "Creativity is intelligence having fun. - Albert Einstein",
  "Innovation distinguishes between a leader and a follower. - Steve Jobs",
  "The secret to creativity is knowing how to hide your sources. - Albert Einstein",
  "Think different. - Apple Inc.",
  "Creativity is just connecting things. - Steve Jobs",
  "Innovation is seeing what everybody has seen and thinking what nobody has thought. - Dr. Albert Szent-Györgyi",
  "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
  "The true sign of intelligence is not knowledge but imagination. - Albert Einstein",
  "Every child is an artist. The problem is how to remain an artist once we grow up. - Pablo Picasso",
  "Innovation comes from people meeting up in the hallways or calling each other at 10:30 at night with a new idea. - Steve Jobs",

  // Passion & Enthusiasm
  "Nothing great in the world has ever been accomplished without passion. - Georg Wilhelm Friedrich Hegel",
  "Passion is energy. Feel the power that comes from focusing on what excites you. - Oprah Winfrey",
  "Follow your passion, it will lead you to your purpose. - Oprah Winfrey",
  "If you feel like there's something out there that you're supposed to be doing, if you have a passion for it, then stop wishing and just do it. - Wanda Sykes",
  "Chase your passion, not your pension. - Denis Waitley",
  "When you have a passion for something then you tend not only to be better at it, but you work harder at it too. - Vera Wang",
  "Every great dream begins with a dreamer. - Harriet Tubman",
  "Do it with passion or not at all. - Rosa Nouchette Carey",
  "Passion will move men beyond themselves, beyond their shortcomings, beyond their failures. - Joseph Campbell",
  "If you can't figure out your purpose, figure out your passion. For your passion will lead you right into your purpose. - Bishop T.D. Jakes",

  // Teamwork & Collaboration
  "Alone we can do so little; together we can do so much. - Helen Keller",
  "Talent wins games, but teamwork and intelligence win championships. - Michael Jordan",
  "None of us is as smart as all of us. - Ken Blanchard",
  "Coming together is a beginning. Keeping together is progress. Working together is success. - Henry Ford",
  "The strength of the team is each individual member. The strength of each member is the team. - Phil Jackson",
  "Great things in business are never done by one person. They're done by a team of people. - Steve Jobs",
  "If you want to go fast, go alone. If you want to go far, go together. - African Proverb",
  "Unity is strength... when there is teamwork and collaboration, wonderful things can be achieved. - Mattie Stepanek",
  "Individual commitment to a group effort--that is what makes a team work, a company work, a society work, a civilization work. - Vince Lombardi",
  "The best teamwork comes from men who are working independently toward one goal in unison. - James Cash Penney",

  // Authenticity & Self-Worth
  "Be yourself; everyone else is already taken. - Oscar Wilde",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
  "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
  "The most powerful thing you can be is yourself. - Lady Gaga",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
  "You yourself, as much as anybody in the entire universe, deserve your love and affection. - Buddha",
  "Be who you are and say what you feel, because those who mind don't matter and those who matter don't mind. - Dr. Seuss",
  "To accept ourselves as we are means to value our imperfections as much as our perfections. - Sandra Bierig",
  "Your self-worth is determined by you. You don't have to depend on someone telling you who you are. - Beyoncé",
  "The worst loneliness is to not be comfortable with yourself. - Mark Twain",

  // Excellence & Quality
  "Excellence is not a skill. It is an attitude. - Ralph Marston",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle",
  "Good is not good where better is expected. - Thomas Fuller",
  "The quality of a person's life is in direct proportion to their commitment to excellence, regardless of their chosen field of endeavor. - Vince Lombardi",
  "Excellence is the gradual result of always striving to do better. - Pat Riley",
  "If you're going to do something, do it with style! - Jason Statham",
  "Whatever is worth doing at all is worth doing well. - Philip Stanhope",
  "The noblest search is the search for excellence. - Lyndon B. Johnson",
  "Excellence is doing ordinary things extraordinarily well. - John W. Gardner",
  "Perfection is not attainable, but if we chase perfection we can catch excellence. - Vince Lombardi",

  // Gratitude & Positivity
  "Gratitude turns what we have into enough. - Anonymous",
  "When you arise in the morning, think of what a precious privilege it is to be alive—to breathe, to think, to enjoy, to love. - Marcus Aurelius",
  "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
  "The more you praise and celebrate your life, the more there is in life to celebrate. - Oprah Winfrey",
  "Gratitude is the fairest blossom which springs from the soul. - Henry Ward Beecher",
  "Be thankful for what you have; you'll end up having more. If you concentrate on what you don't have, you will never, ever have enough. - Oprah Winfrey",
  "Appreciation is a wonderful thing. It makes what is excellent in others belong to us as well. - Voltaire",
  "The roots of all goodness lie in the soil of appreciation for goodness. - Dalai Lama",
  "Appreciate where you are in your journey, even if it's not where you want to be. Every season serves its purpose. - Anonymous",
  "What you focus on expands, and when you focus on the goodness in your life, you create more of it. - Oprah Winfrey",

  // Balance & Wellness
  "Take care of your body. It's the only place you have to live. - Jim Rohn",
  "The key is not to prioritize what's on your schedule, but to schedule your priorities. - Stephen Covey",
  "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
  "Happiness is not a matter of intensity but of balance, order, rhythm and harmony. - Thomas Merton",
  "Balance is not something you find, it's something you create. - Jana Kingsford",
  "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity. - John F. Kennedy",
  "Your calm mind is the ultimate weapon against your challenges. - Bryant McGill",
  "The best and safest thing is to keep a balance in your life, acknowledge the great powers around us and in us. If you can do that, and live that way, you are really a wise man. - Euripides",
  "Health is a state of complete harmony of the body, mind and spirit. - B.K.S. Iyengar",
  "Just as your car runs more smoothly and requires less energy to go faster and farther when the wheels are in perfect alignment, you perform better when your thoughts, feelings, emotions, goals, and values are in balance. - Brian Tracy",

  // Legacy & Impact
  "What we do now echoes in eternity. - Marcus Aurelius",
  "Carve your name on hearts, not tombstones. A legacy is etched into the minds of others and the stories they share about you. - Shannon L. Alder",
  "The greatest use of life is to spend it for something that will outlast it. - William James",
  "Life is no brief candle to me. It is a sort of splendid torch which I have got a hold of for the moment, and I want to make it burn as brightly as possible before handing it onto future generations. - George Bernard Shaw",
  "We make a living by what we get, but we make a life by what we give. - Winston Churchill",
  "Your story is the greatest legacy that you will leave to your friends. It's the longest-lasting legacy you will leave to your heirs. - Steve Saint",
  "The things you do for yourself are gone when you are gone, but the things you do for others remain as your legacy. - Kalu Ndukwe Kalu",
  "Legacy is not leaving something for people. It's leaving something in people. - Peter Strople",
  "The greatest legacy one can pass on to one's children and grandchildren is not money or other material things accumulated in one's life, but rather a legacy of character and faith. - Billy Graham",
  "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. - Maya Angelou",

  // Achievement & Success
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
  "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
  "Would you like me to give you a formula for success? It's quite simple, really: Double your rate of failure. - Thomas J. Watson",
  "The difference between successful people and very successful people is that very successful people say 'no' to almost everything. - Warren Buffett",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "Don't be distracted by criticism. Remember--the only taste of success some people get is to take a bite out of you. - Zig Ziglar",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure. - Colin Powell",

  // Inspiration & Motivation
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "Magic is believing in yourself. If you can make that happen, you can make anything happen. - Johann Wolfgang von Goethe",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "When you have a dream, you've got to grab it and never let go. - Carol Burnett",
  "Inspiration comes from within yourself. One has to be positive. When you're positive, good things happen. - Deep Roy",
  "Sometimes the smallest step in the right direction can be the biggest step of your life. - Emma Stone",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "Don't let anyone tell you what you can't do. Follow your dreams and persist. - Barack Obama",
  "Nothing is impossible. The word itself says 'I'm possible!' - Audrey Hepburn",
  "Keep your eyes on the stars, and your feet on the ground. - Theodore Roosevelt",

  // Time Management & Productivity
  "Time is more valuable than money. You can get more money, but you cannot get more time. - Jim Rohn",
  "The bad news is time flies. The good news is you're the pilot. - Michael Altshuler",
  "Lost time is never found again. - Benjamin Franklin",
  "Time management is life management. - Robin Sharma",
  "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
  "The way we spend our time defines who we are. - Jonathan Estrin",
  "Either you run the day or the day runs you. - Jim Rohn",
  "Time is what we want most, but what we use worst. - William Penn",
  "Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin. - Mother Teresa",
  "The key is in not spending time, but in investing it. - Stephen R. Covey",

  // Personal Development
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
  "Be so busy improving yourself that you have no time to criticize others. - Chetan Bhagat",
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Investing in yourself is the best investment you will ever make. It will not only improve your life, it will improve the lives of all those around you. - Robin Sharma",
  "Personal development is a major time-saver. The better you become, the less time it takes you to achieve your goals. - Brian Tracy",
  "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
  "You are your greatest asset. Put your time, effort and money into training, grooming, and encouraging your greatest asset. - Tom Hopkins",
  "The most difficult thing is the decision to act, the rest is merely tenacity. - Amelia Earhart",
  "Life is growth. If we stop growing, technically and spiritually, we are as good as dead. - Morihei Ueshiba",

  // Challenges & Growth
  "In the middle of difficulty lies opportunity. - Albert Einstein",
  "The greater the obstacle, the more glory in overcoming it. - Molière",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "Don't wish it were easier. Wish you were better. - Jim Rohn",
  "The gem cannot be polished without friction, nor man perfected without trials. - Chinese Proverb",
  "Life's challenges are not supposed to paralyze you; they're supposed to help you discover who you are. - Bernice Johnson Reagon",
  "Problems are not stop signs, they are guidelines. - Robert H. Schuller",
  "Strength does not come from winning. Your struggles develop your strengths. - Arnold Schwarzenegger",
  "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy. - Martin Luther King Jr.",
  "Every adversity carries with it the seed of an equal or greater benefit. - Napoleon Hill",
  
  // Additional Life Wisdom
  "Life isn't about finding yourself. Life is about creating yourself. - George Bernard Shaw",
  "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate. - Ralph Waldo Emerson",
  "Life shrinks or expands in proportion to one's courage. - Anais Nin",
  "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain"
];

export default motivationalQuotes;